repository: HenryFMa/mhf

description: Henry Ma's Website

assets_url_cdn: https://cdn.jsdelivr.net/gh/HenryFMa/mhf

theme: jekyll-theme-modernist

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions